### ISSUE TITLE
[質問]このPatchはArchLinux向けですか？

### ISSUE THREAD

**Issue by rkarsnk** [tattsan/PKGBUILD-uim-skk-utf8#2]
このPatchは、ArchLinux向けに書いたものでしょうか？

**Comment by tattsan** [comment]
uim-skk-1.8.8-utf8-?.patch などは uim  のソースコードに対するパッチなので、
環境には依存しません。

Arch Linux に依存するのは PKGBUILD ですが、これは只のシェルスクリプト
ですので他の環境に移植するのは簡単だと思います。

**Comment by rkarsnk** [comment]
ありがとうごさいます。
Debian用のUTF対応uim-skkの野良パッケージを作る参考にさせていただきます。
